# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: decbba80d0166c31f1f7cd2d4947dfab4f40ac226b0965edbe2b0c54832ee30f052b78a97098758669a90df7d97c49f11edf9b9f417f4d933328f746b14d1e3e

test:
  secret_key_base: 7f46a6e8745e279356041c3dbfdf1f5d9324808e94b2c5ddcc8e4a8df7604ab85b28029e222cd670cca370f16f2e933855cde90588a5dd63729da594f1f4c791

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
